FROM node:18.0.0-alpine3.15 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV REACT_APP_API_URL=http://104.248.250.255:8001
RUN npm run build

FROM nginx:1.19-alpine
COPY --from=build-stage /app/build/ /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]